"""empty message

Revision ID: b8a736658788
Revises: 
Create Date: 2020-03-08 00:56:17.791863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8a736658788'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=6), nullable=True),
    sa.Column('insert_date_time', sa.DateTime(), nullable=True),
    sa.Column('eval', sa.Enum('OVERVALUED', 'UNDERVALUED', 'NEAR_FAIR_VALUE', name='evaluation'), nullable=True),
    sa.Column('recmd_short', sa.Enum('SELL', 'HOLD', 'BUY', name='recomendation'), nullable=True),
    sa.Column('recmd_mid', sa.Enum('SELL', 'HOLD', 'BUY', name='recomendation'), nullable=True),
    sa.Column('recmd_long', sa.Enum('SELL', 'HOLD', 'BUY', name='recomendation'), nullable=True),
    sa.Column('pattern', sa.Enum('Bearish', 'Bullish', 'Neutral', name='pattern'), nullable=True),
    sa.Column('pattern_type', sa.String(length=50), nullable=True),
    sa.Column('est_return', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
